name: Setup and Run Windows 11 VM Workflow

on: [push]

jobs:
  setup-run-vm:
    runs-on: windows-latest

    steps:
    - name: Download Windows 11 22H2 ISO
      shell: powershell
      run: |
        $outputPath = "C:\temp\Win11_22H2_x64.iso"
        $url = "https://software-download.microsoft.com/db/Win11_22H2_English_x64v1.iso"
        Invoke-WebRequest -Uri $url -OutFile $outputPath
        Write-Output "ISO downloaded to $outputPath"

    - name: Create and Manage VM with PowerShell
      shell: powershell
      run: |
        $vmName = "Win11-6oee"
        $vmMemoryGB = 64
        $vmProcessorCount = 8
        $vmDiskPath = "C:\HyperV\VirtualHardDisks\$vmName.vhdx"
        $vmIsoPath = "C:\temp\Win11_22H2_x64.iso"
        $vmDiskSizeBytes = 1TB

        # Creare director pentru disc daca nu exista
        if(-not (Test-Path (Split-Path $vmDiskPath))) {
          New-Item -ItemType Directory -Path (Split-Path $vmDiskPath) -Force
        }

        # Creare disc virtual 1TB
        New-VHD -Path $vmDiskPath -SizeBytes $vmDiskSizeBytes -Dynamic

        # Creare VM nou
        New-VM -Name $vmName -MemoryStartupBytes (${vmMemoryGB}GB) -Generation 2 -NewVHDPath $vmDiskPath

        # Seteaza procesor
        Set-VMProcessor -VMName $vmName -Count $vmProcessorCount

        # Atașează ISO
        Add-VMDvdDrive -VMName $vmName -Path $vmIsoPath

        # Setează boot de pe DVD la primul boot
        Set-VMFirmware -VMName $vmName -BootOrder (Get-VMFirmware -VMName $vmName).BootOrder | Where-Object { $_.Device -eq "CD" }

        # Porneste VM
        Start-VM -Name $vmName

        # Pause sa permita instalare manuala windows sau unattended setup (de aici automatizarea în interior e complexă)
        Write-Output "Așteptați să instalați Windows 11 pe VM manual sau scriptat."

        # Sleep 600 secunde (10 minute) simulare timp instalare (ajustabil pentru instalare unattended)
        Start-Sleep -Seconds 600

        # Instalează Tailscale și RustDesk în VM folosind PowerShell Direct (presupune că VM e configurat)
        Invoke-Command -VMName $vmName -ScriptBlock {
          Invoke-WebRequest -Uri "https://tailscale.com/install.ps1" -UseBasicParsing | Invoke-Expression
          tailscale up --authkey="YOUR_AUTH_KEY" --accept-routes
          Start-Process -FilePath "powershell.exe" -ArgumentList "winget install --id RustDesk.RustDesk -e -h" -Wait
          $confPath = "$env:APPDATA\RustDesk\rustdesk.conf"
          Start-Sleep -Seconds 10
          if (Test-Path $confPath) {
            $configContent = Get-Content $confPath -Raw
            $newContent = $configContent -replace '"password":".*"', '"password":"ParolaTare123"'
            Set-Content -Path $confPath -Value $newContent
          }
          Start-Process "C:\Program Files\RustDesk\rustdesk.exe"
        }

        # Ruleaza VM 21600 secunde (6 ore)
        Start-Sleep -Seconds 21600

        # Opreste VM dupa 6 ore
        Stop-VM -Name $vmName -Force

        Write-Output "Workflow complet, VM oprit după 6 ore."
        
